---
- homebrew: name={{ item }} state=latest
  with_items:
  - rbenv
  - ruby-build

- homebrew: name={{ item }} state=latest
  with_items:
  - readline
  - openssl

- lineinfile:
    path: ~/.bash_profile
    insertafter: EOF
    state: present
    line: 'eval "$(rbenv init -)"'

- shell: >
    eval "$(rbenv init -)";
    rbenv global
  register: rbenv_global_version
  changed_when: false

- shell: >
    eval "$(rbenv init -)";
    rbenv global {{ rbenv_ruby_version }}
  when: rbenv_global_version.stdout != rbenv_ruby_version

# NOTE: We must set user_install=no to install gems to ~/.rbenv/versions/{{ rbenv_ruby_version }}/lib/ruby/gems/.
# If not, gems are installed to /usr/local/lib/ruby/gems/.
- gem: name={{ item }} state=latest user_install=no executable=${HOME}/.rbenv/shims/gem
  notify: rbenv rehash
  with_items: "{{ rbenv_global_gems }}"